#!/bin/bash
#SBATCH -A CS4380_5351_7332 # account name
#SBATCH -J p1_fractal       # job name
#SBATCH -o p1_fractal.%j    # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p gpu              # queue name
#SBATCH -t 00:01:00         # expected maximum runtime (hh:mm:ss)

date

./fractal 20000 1

date

